# Generated by Django 5.2.13 on 2026-09-18 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, help_text='Generated audio attached to an audio post.', null=True, upload_to='posts/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('prompt', 'Prompt'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=20),
        ),
    ]
