# Generated by Django 6.1.1 on 2026-09-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
