# Generated by Django 6.1.1 on 2026-09-25 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_post_audio_alter_post_post_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='https://api.gapgpt.app/v1', help_text='OpenAI-compatible API root, e.g. https://api.gapgpt.app/v1')),
                ('api_key', models.CharField(blank=True, default='', help_text='Bearer token for the provider. Leave empty to keep generation disabled.', max_length=255)),
                ('model', models.CharField(default='gapgpt/z-image', help_text='Model id sent to the provider, e.g. gapgpt/z-image', max_length=100)),
                ('image_size', models.CharField(default='1024x1024', help_text='Size requested from the provider, e.g. 1024x1024', max_length=20)),
                ('timeout_seconds', models.PositiveIntegerField(default=120, help_text='How long to wait for the provider before giving up.')),
                ('is_enabled', models.BooleanField(default=True, help_text="Turn the studio's generate button off without deleting the key.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider settings',
                'verbose_name_plural': 'AI provider settings',
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated_images/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('provider_model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_post', models.ForeignKey(blank=True, help_text='The prompt post this image was remixed from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='imagegen_ge_user_id_b1454f_idx'), models.Index(fields=['status', '-created_at'], name='imagegen_ge_status_68aafa_idx')],
            },
        ),
    ]
